
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # pull_request:
  #   branches: [ dev ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ master,dev, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   build:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
     steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Build image
      #   run: docker build . --file Dockerfile --tag mcu01050435/test  
      - uses: actions/checkout@v2
      - name: Set $VERSION variable
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF |cut -d / -f 3)
      - name: Get branch name
        run: echo 'The branch name is' ${{ steps.version.outputs.VERSION }}
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag pimq/parameter-influxdb:${{ steps.version.outputs.VERSION }}
      # - name: Push image
      #   run: docker push pimq/parameter-influxdb:${{ steps.version.outputs.VERSION }}